# lmage Worker - 图像生成
name = "lmage"
main = "lmage-worker.js"
compatibility_date = "2024-01-01"

# 绑定 D1 数据库（与 chat-app-db 共用同一个数据库）
[[d1_databases]]
binding = "DB"
database_name = "chat-app-db"
database_id = "46260ff3-1d5a-459a-a8d8-33d329d18176"

# 绑定 KV 存储
[[kv_namespaces]]
binding = "IMAGE_GALLERY"
id = "a7300b1881eb4409957e93b9492379db"
